# Generated by Django 4.0.4 on 2022-05-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
